version: '3.8'

services:
  app:
    container_name: docker-react-container
    image: docker-react-i
    build: 
      context: ./Frontend/bytejack_frontend
    ports:
      - "3000:3000"
    # depends_on:
    #   backend:
    #     condition: service_healthy
    #     restart: true
  backend:
    build: ./backend
    image: pp
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
  db:
    build: ./db
    image: pppp
    ports:
      - "3306:3306"

